name: flutter_uploader
description: A plugin for creating and managing upload tasks with optional background exection support.
version: 3.0.0-beta.5
homepage: https://github.com/hayatkhan67/flutter_uploader
maintainer: Hayat Khan

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.15
  mockito: ^5.4.6
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bluechilli.flutteruploader
        pluginClass: FlutterUploaderPlugin
      ios:
        pluginClass: FlutterUploaderPlugin

false_secrets:
  - example/ios/Runner/GoogleService-Info.plist
